### PR TITLE
Added git branch command to readme

### PR DESCRIPTION
**Pull request by moorhead212**
Added the branch command showing how to crate a new  
#15

### CODE REVIEW

**Comment by tedgravlin** [comment]
Please format the command by putting this symbol ` around it:

**Review by tedgravlin — APPROVED** [review]
Looks good to me!

**Comment by sjiang1** [comment]
I know the pull request is closed and technically, you finished the assignment. But the formatting of the Git Command is wrong. :joy:

Screenshot 2023-02-23 at 7 07 23 AM

**Comment by moorhead212** [comment]
Dang it! Do I just re-open my branch to fix it and resend the pull request?
I blame Ted, he made me do it! 😩

**Comment by sjiang1** [comment]
According to StackOverflow, once the pull request is merged, it can't be re-opened. So, if you want to fix it, you can create another branch and do a pull request. 

By the way, the formatting code should be:
```
`git branch` (this will create ...)
```

**Comment by moorhead212** [comment]
Sorry, I lost power from all the ice fun! Would you like me to re-do the
branch and pull? For some reason when I did the ‘ surrounding the command
it ignored the < > portion of the command which left that weird space.

**Comment by sjiang1** [comment]
That's fine. Let's just leave it there.

**Pull request merged**
