### PR TITLE
[doc] Add a description for repo

### PR DESCRIPTION
**Pull request by SalvadorMedinaRuiz**
I added the following things into README:
1. I just changed "This repository is for students to practice GitHub flow" to "This repository is for me to practice GitHub flow"

issue #5

### CODE REVIEW

**Review by sjiang1 — CHANGES_REQUESTED** [review]
Please check the content in README.md:

> add commits: students need to write in this README.md file to add their own Git command's helper message

Please add a Git command helper message to the README.

A Git command helper message example:
`git add -p README.md`: Interactively stage hunks of changes in README.md

**Comment by SalvadorMedinaRuiz** [comment]
Updated the README.md

**Review by sjiang1 — APPROVED** [review]
Looks fine!

**Comment by sjiang1** [comment]
Technically, I need to merge but I forgot. It's ok for this assignment.

**Pull request merged**
