### PR TITLE
Added git log command to ReadMe.md

### PR DESCRIPTION
**Pull request by ppaliani**
Also included information about --all, --graph, and --oneline options.

### CODE REVIEW

**Review by sjiang1 — CHANGES_REQUESTED** [review]
The command looks good. Make sure you solve the conflict first.

**Review by sjiang1 — CHANGES_REQUESTED** [review]
My bad. Probably no conflict. Please just add an emoji at the end of your command.

**Comment by ppaliani** [comment]
> My bad. Probably no conflict. Please just add an emoji at the end of your command.

I'm not sure what you mean by 'add an emoji at the end of your command'. Would you like me to just make one last commit and add ':)' afterwards?

**Review by sjiang1 — APPROVED** [review]
All looks good!

**Comment by sjiang1** [comment]
Please delete your branch

**Pull request merged**
