### PR TITLE
[doc] Add a desc for git switch command

### PR DESCRIPTION
**Pull request by ctrotta23**
I added the following text into the README file:
`git switch <branch name>` This command allows you to switch between branches in git

### CODE REVIEW

**Comment by hosulliv** [comment]
This looks great! You could always add more following a git switch, but for demo purposes this is great!!

**Review by sjiang1 — CHANGES_REQUESTED** [review]
Looks good! Please add an emoji, e.g. 😄 at the end of message 
`:smile:`

**Review by sjiang1 — CHANGES_REQUESTED** [review]
Looks good! Please add an emoji at the end of your message.
`:smile:` :smile:

**Review by sjiang1 — APPROVED** [review]
Approve!

**Comment by sjiang1** [comment]
Please delete the branch.

**Pull request merged**
