### PR TITLE
Ladaweb/update readme file

### PR DESCRIPTION
**Pull request by ladaweb**
I added the original file back. Please, review my pull request

### CODE REVIEW

**Review by sjiang1 — COMMENTED** [review]
Looks good. There's an update in the main branch, so you need to solve the conflict in your branch first before I approve.

When a conflict shows on your pull request, please:

1) `git pull` on your main branch so that your main branch is up to date
2) then, on your branch, merge with main, and solve the conflict
3) `git push` your branch, then the pull request will be updated

**Comment by ladaweb** [comment]
Good morning! I resolved conflicts and pushed the changes. Do I need to add
something more?

**Review by sjiang1 — APPROVED** [review]
OK!

**Comment by sjiang1** [comment]
All good. Please delete your branch.

**Comment by ladaweb** [comment]
I did. Thank you!

**Pull request merged**
