### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by HamzMalk**

### CODE REVIEW

**Comment by HamzMalk** [comment]
assignee

**Comment by HamzMalk** [comment]
pull

**Review by sjiang1 — CHANGES_REQUESTED** [review]
OK. Looks good. Please add an emoji at the end of line 61. Also, fix the merge conflict.

**Comment by HamzMalk** [comment]
I've commited the changes you requested

**Review by HamzMalk — COMMENTED** [review]
Committed the changes as requested

**Review by sjiang1 — APPROVED** [review]
Good work!

**Comment by sjiang1** [comment]
Don't forget to delete this branch, and please resubmit on Canvas.

**Pull request merged**
