### PR TITLE
Create ThisIsMyCommit.txt

### PR DESCRIPTION
**Pull request by DerenB**
Creating my first pull request for creating a documentation file.

### CODE REVIEW

**Review by sjiang1 — CHANGES_REQUESTED** [review]
Instead of adding a new file, please add your Git Command example in the README.md

Something like this: https://github.com/COSC381-2023Winter/github-flow-demo/pull/10/files

**Comment by DerenB** [comment]
Removed the unnecessary file and added changes to the ReadMe File

**Review by sjiang1 — APPROVED** [review]
This is a duplicate command helper message. But for this assignment's purpose, it's ok.

**Comment by sjiang1** [comment]
Please delete the branch.

**Pull request merged**
